version: '3.8'

services:
  redis:
    image: redis:6.0.9
    container_name: redis_6_0_9
    restart: always
    environment: 
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:
    - '26379:6379'
    volumes:
      - './assets/data:/data'
      - './assets/conf:/etc/conf'
    #环境变量
    privileged: true
    
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    container_name: phpredisadmin_latest
    restart: always
    depends_on: 
      - redis
    environment: 
      REDIS_1_HOST: 10.0.0.2
      REDIS_1_NAME: redis_6_0_9
      REDIS_1_PORT: '26379'
      ADMIN_USER: root
      ADMIN_PASS: hp_root_123
    ports:
    - '26380:80'


